### ISSUE TITLE
Edges for sshist

### ISSUE THREAD

**Issue by johnchanck** [shimazaki/density_estimation#1]
Hello,

I believe I may have found a minor bug in your evaluation of edges on 
[line 93 of sshist.m](https://github.com/shimazaki/density_estimation/blob/master/matlab/sshist.m#L93):
`edges = linspace(x_min,x_max,optN);  % Optimal segmentation`

should it not instead be:
`edges = linspace(x_min,x_max,optN + 1);  % Optimal segmentation`

since optN is the number of bins and not the number of edges?

Thank you for the code, I am finding it very useful.

John

**Comment by shimazaki** [comment]
thanks a lot! I updated the code. - hideaki

**Comment by johnchanck** [comment]
Awesome!
